9.テキスト教材のCSVインポート機能を実装
yanbaru-expert/team_project_43 pull request #29
Opened 2021-02-12 14:44 UTC by imaizumi-satoko

close #9

## 実装内容

- テキスト教材のCSVを読み込み、textsテーブルにデータを投入する処理を実装

## 参考資料

- CSVデータインポート機能
  - [やんばるCODEアプリ](https://www.yanbaru-code.com/texts/217)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-13 12:16 UTC, T-Tsujii requested changes

2021-02-13 12:16 UTC, T-Tsujii commented on lib/autoloads/import_csv.rb
> +  def self.textimport(path)
```suggestion
  def self.text_import(path)
```

2021-02-13 12:16 UTC, T-Tsujii commented on db/seeds.rb
> +ImportCsv.textimport("db/csv_data/text_data.csv")
```suggestion
ImportCsv.text_import("db/csv_data/text_data.csv")
```

2021-02-13 12:16 UTC, T-Tsujii commented on lib/autoloads/import_csv.rb
> +    puts "TEXTへCSVデータ投入完了"
もう少しわかりやすい表示にしましょう。

```suggestion
    puts "テキスト教材のCSVデータ投入に成功しました。"
```

2021-02-13 12:30 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-13 12:39 UTC, ao21 approved these changes
LGTMです！

2021-02-14 01:25 UTC, zenfumi approved these changes
LGTMです！

2021-02-14 02:08 UTC, gorgonzola731 approved these changes
LGTMです。

2021-02-14 07:30 UTC, merged