管理者画面の実装
yanbaru-expert/team_project_43 pull request #36
Opened 2021-02-14 13:43 UTC by ao21

## 14

close #14

## 実装内容

- Active Admin を導入
  - ユーザー、動画、テキスト教材を管理者画面から追加できるように設定 
  - 管理者画面以外のスタイルに影響が出ないように対処
- `db/seeds.rb` をissue6と同様の形式（何度実行してもエラーが出ない形式）に修正
  - 開発環境に限定する条件を削除

## 参考資料

  - [やんばるCODE教材 管理者画面](https://www.yanbaru-code.com/texts/220)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-15 03:37 UTC, T-Tsujii requested changes

2021-02-15 03:37 UTC, T-Tsujii commented on app/admin/users.rb
> +  permit_params :email, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at
これですとユーザーの追加などができません。
`app/admin/admin_users.rb`を参考にして下さい。

変更前後でどう変わるかを管理者画面で実際に確かめてみましょう。

2021-02-15 03:37 UTC, T-Tsujii commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com') do |admin_user|
ユーザーを作成する箇所の上に移動しませんか？
乱雑に配置するのはよろしくないと思います。

2021-02-15 04:09 UTC, ao21 commented on app/admin/users.rb
> +  permit_params :email, :encrypted_password, :reset_password_token, :reset_password_sent_at, :remember_created_at
追加できるようになりました！アドバイスありがとうございます。

2021-02-15 04:12 UTC, ao21 commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com') do |admin_user|
ユーザー系の記述とインポート系の記述でまとめました！
変数は一番上が適切かと思い、
`EMAIL`と`PASSWORD`変数 → AdminUserの作成 → ユーザの作成
という順番にしましたが、良い配置かご確認いただきたいです🙇‍♂️

2021-02-15 04:19 UTC, T-Tsujii approved these changes

2021-02-15 04:19 UTC, T-Tsujii commented on db/seeds.rb
> +end
場所はこれでOKです。Userの場合と同様，

```
ADMIN_EMAIL = 'admin@example.com'
ADMIN_PASSWORD = 'password'
```

を用意してもよいでしょう。お任せします。

2021-02-15 04:23 UTC, ao21 commented on db/seeds.rb
> +end
記述を揃えたほうが見やすいので、修正します！ありがとうございます。

2021-02-15 15:00 UTC, zenfumi approved these changes
LGTMです！

2021-02-16 03:58 UTC, gorgonzola731 approved these changes
LGTMです！

2021-02-16 05:32 UTC, imaizumi-satoko approved these changes
LGTMです！

2021-02-16 05:53 UTC, merged