17.動画教材一覧ページを実装
yanbaru-expert/team_project_43 pull request #42
Opened 2021-02-18 02:46 UTC by imaizumi-satoko

close #17 

## 実装内容

- Rails動画教材の一覧ページを作成
  - ナビバーの動画教材ページへのリンクが機能するようルーティングを設定
  - 動画用のコントローラーを作成　
    - Rails動画教材で表示するジャンルを["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"]のみに設定
  - 動画教材のビューファイルのスタイルをBootstrapを用いて修正

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-18 03:31 UTC, T-Tsujii requested changes

2021-02-18 03:31 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"])
順番も指定した方がよいですね。

2021-02-18 03:31 UTC, T-Tsujii commented on config/routes.rb
> +  resources :movies
`only` で必要なルーティングのみに絞りましょう。

2021-02-18 12:20 UTC, imaizumi-satoko commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["Basic", "Git", "HTML&CSS", "Ruby", "Ruby on Rails"])
ありがとうございます！修正いたします。

2021-02-18 12:21 UTC, imaizumi-satoko commented on config/routes.rb
> +  resources :movies
確認しました。修正いたします。

2021-02-18 21:51 UTC, T-Tsujii requested changes

2021-02-18 21:51 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +        <iframe src=<%= movie.url %> frameborder="0" height="50%"></iframe>
この動画埋め込みようの `iframe` タグは YouTube の「共有」--> 「埋め込み」で得られるリンクをベースにした方がよいですね。

2021-02-19 23:15 UTC, ao21 approved these changes
LGTMです！

2021-02-20 00:33 UTC, zenfumi approved these changes
LGTMです！

2021-02-20 04:04 UTC, gorgonzola731 approved these changes
LGTMです！

2021-02-21 07:00 UTC, imaizumi-satoko commented on app/views/movies/index.html.erb
> +        <iframe src=<%= movie.url %> frameborder="0" height="50%"></iframe>
確認しました。

2021-02-21 07:05 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-21 07:08 UTC, merged