Railsテキスト教材一覧ページ「検索機能」の実装
yanbaru-expert/team_project_43 pull request #46
Opened 2021-02-21 05:37 UTC by zenfumi

close #23

## 実装内容

- 検索機能実装
  - 検索フォーム設置
  - 検索機能のjsファイル作成

## 参考資料

- ログイン機能
  - [やんばるCODEアプリ](https://www.yanbaru-code.com/texts/216)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考（必要があれば）
- jsファイルの動作はコンソール上で確認しています。
- 検索対象のHTML生成されていない状態なので検索機能の絞り込み動作確認ができていませんが、別のRailsアプリ環境で同じ　HTML構造を使用し絞り込みができていることは確認しております。

2021-02-21 06:12 UTC, T-Tsujii requested changes

2021-02-21 06:12 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +.input-group{
Bootstrapのクラスに安易にスタイルを入れるのは控えましょう。
他のページに影響が出る可能性があります。

2021-02-21 09:08 UTC, zenfumi commented on app/assets/stylesheets/application.scss
> +.input-group{
w-50を使ったのですが、こちらもクラスにスタイルを変更しているのと一緒でしょうか？

2021-02-21 12:14 UTC, T-Tsujii requested changes

2021-02-21 12:14 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  max-width:350px;
width を % で指定されるなら，`max-width` は必要ないですね。
あと，下側の空きが小さすぎますので，margin-bottomを入れた方がよいと思います。

```suggestion
  width: 70%;
```

2021-02-21 12:23 UTC, zenfumi commented on app/assets/stylesheets/application.scss
> +  max-width:350px;
WEBサイトの幅だとwidth: 70%;だと大きすぎるので、max-width:350px;を指定しました。実際のアプリも検索窓の大きさが一定に近い為、一定になるようにとしたのですが、ご意見お伺いしたいです。

2021-02-21 12:33 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  max-width:350px;
> WEBサイトの幅だとwidth: 70%;だと大きすぎるので、max-width:350px;を指定しました。
すみません，関係ありましたね。残しておいて下さい。

2021-02-21 12:42 UTC, zenfumi commented on app/assets/stylesheets/application.scss
> +  max-width:350px;
再度、ご確認頂き有難うございます！
インデントとmarginの修正プルリクをこれから出しますので、お願い致します。

2021-02-21 12:54 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-22 04:20 UTC, ao21 approved these changes
LGTMです！

2021-02-22 04:57 UTC, gorgonzola731 approved these changes
LGTMです！

2021-02-22 11:45 UTC, imaizumi-satoko approved these changes
LGTMです。

2021-02-23 00:56 UTC, merged