Rails動画教材ページ「ページネーション」の実装
yanbaru-expert/team_project_43 pull request #47
Opened 2021-02-21 14:21 UTC by imaizumi-satoko

close #26

## 実装内容

- kaminariを導入しページネーションを実装
  - generateコマンドでkaminariのviewを追加
  - ページネーションの位置を修正

## 参考資料

- Bootstrapにてkaminariを使用する方法
  - 【Rails】kaminari + Bootstrapで見た目を整え、ページネーションを中央にする(https://qiita.com/shun-takahashi/items/ed45d76e0f011e4f5b7b)

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-02-21 21:59 UTC, T-Tsujii requested changes
ページネーションの実装はOKなのですが，2ページ目以降のレベル表示を確認してみましょう。
`offset_value` を使用するのがポイントです。

2021-02-22 12:07 UTC, T-Tsujii approved these changes
LGTMです！

2021-02-22 12:35 UTC, zenfumi approved these changes
LGTMです。

2021-02-22 13:09 UTC, ao21 approved these changes
LGTMです！

2021-02-23 04:23 UTC, gorgonzola731 approved these changes
LGTMです！

2021-02-24 01:33 UTC, merged