マイページのテキスト進捗管理ページの実装
yanbaru-expert/team_project_43 pull request #57
Opened 2021-02-27 00:58 UTC by ao21

## 54

close #54 

## 実装内容

- UserモデルにTextモデル、Readモデルとの関連付けを追加
- my_pages のルーティングを設定し、ナビバーにリンクを追加
- Userモデルに進捗率の計算メソッドを追加
- コントローラに進捗のカウントを追加
- my_pages一覧ページに Bootstrap の ProgressBar を実装

## 参考資料
- モデルの関連付け
  - [やんばる教材（モデルの関連付け(多対多)）](https://www.yanbaru-code.com/texts/297)
  - [Railsガイド（ActiveRecordの関連付け）](https://railsguides.jp/association_basics.html)
- 進捗バー
  - [（公式）Bootstrap](https://getbootstrap.jp/docs/4.3/components/progress/)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-04 09:17 UTC, T-Tsujii requested changes

2021-03-04 09:17 UTC, T-Tsujii commented on app/models/genre.rb
> +  def self.progress_data(user)
テキスト教材の進捗ですので，Textモデルに配置した方がよいと思います。
（動画教材の進捗で命名に困ることになるでしょう）

2021-03-04 09:17 UTC, T-Tsujii commented on db/migrate/20210304013614_insert_initial_genres.rb
> +  def change
この操作はロールバックできないので， `up` にしておきましょう。

```suggestion
  def up
```

2021-03-04 09:17 UTC, T-Tsujii commented on app/models/text.rb
> +      return 0
`return` はなくてもよいですね。

```suggestion
      0
```

2021-03-04 09:17 UTC, T-Tsujii commented on app/models/text.rb
> +      ( read_count.to_f / total_count.to_f  * 100.0 ).to_i
先に100をかけておけば整数になりますね。

```suggestion
      ( read_count * 100) / total_count
```

2021-03-05 01:23 UTC, ao21 commented on app/models/genre.rb
> +  def self.progress_data(user)
動画教材の進捗の実装への対応が抜けていました🙇‍♂️

2021-03-05 01:53 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-05 13:34 UTC, zenfumi approved these changes
LGTMです！

2021-03-06 05:29 UTC, gorgonzola731 approved these changes
LGTMです！

2021-03-06 08:38 UTC, imaizumi-satoko approved these changes
LGTMです！

2021-03-06 12:00 UTC, merged