LINE詳細ページ作成
yanbaru-expert/team_project_43 pull request #62
Opened 2021-03-02 12:15 UTC by zenfumi

close #53 

## 実装内容

- テキストをマークダウン形式で表示
 - markdownメソッドを使用
 - 幅指定のmargin 0 autoで中央揃え(bootstrapでは、mx-auto)

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-02 14:41 UTC, T-Tsujii approved these changes

2021-03-02 14:41 UTC, T-Tsujii commented on app/views/lines/show.html.erb
> +<div class="mx-auto" style="width: 500px;">
できれば， `application_helper.rb` の `max_width` メソッドで共通化してみてください。

2021-03-04 06:59 UTC, T-Tsujii requested changes

2021-03-04 06:59 UTC, T-Tsujii commented on app/helpers/application_helper.rb
> +      "mx-auto"
この`max_width` は `application.html.erb` で使用しています。構造を確認してみてください。

```suggestion
      "mw-md"
```

2021-03-04 06:59 UTC, T-Tsujii commented on app/views/lines/show.html.erb
> +</div>
```suggestion
<%= markdown(@line.content) %>
```

2021-03-04 07:34 UTC, zenfumi commented on app/helpers/application_helper.rb
> +      "mx-auto"
・max_width がapplication.html.erb で使用されていることは確認しており、
それに対しては、else後の "mw-xl"をそのまま適用できるようにしました。

・こちらmw-mdにすると、中央揃えが効かなくなりテキストが少し左寄りになってしまう為、
あえてmx-autoにしました。
→最大幅のメソッドなので、それに合わせてmw-mdを使用したかったのですが。

誤って考えてるかもしれません。コメント頂けると有難いです。

2021-03-04 07:34 UTC, zenfumi commented on app/views/lines/show.html.erb
> +</div>
・こちら<div class="<%= max_width%>" style="width: 500px;">も削除してしまうのでしょうか？
→style="width: 500px;は、mw-mdを設定して削除されるのは理解できるのですが、<%= max_width%>を削除してしまうのが理解できないです。

2021-03-04 09:19 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-06 02:35 UTC, ao21 approved these changes
LGTMです。

2021-03-07 00:24 UTC, imaizumi-satoko approved these changes
LGTMです！

2021-03-09 03:51 UTC, gorgonzola731 approved these changes
LGTMです！

2021-03-09 08:32 UTC, merged