モデルスペック(Movieモデルの実装)
yanbaru-expert/team_project_43 pull request #84
Opened 2021-03-17 12:31 UTC by ao21

## 83
close #83 

## 実装内容

- FactoryBotでテスト対象のMovieのデータを作成
  - テスト(スペック)ファイルを作成
  - 存在するかどうかのバリデーション等のテスト

## 参考資料
- RSpec（モデルスペック )
  - [やんばるCODE教材（RSpec（factory_bot_railsの基礎））](https://www.yanbaru-code.com/texts/299)
  - [やんばるCODE教材（RSpec（モデルスペック ））](https://www.yanbaru-code.com/texts/300)
- [Faker 公式リファレンス](https://github.com/faker-ruby/faker)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-17 12:57 UTC, T-Tsujii approved these changes
バリデーションについてはLGTMです。

Movieモデルにはいくつかメソッドがありますので，可能ならバリデーション以外のモデルスペック にも挑戦されるとよいですね。

2021-03-19 10:07 UTC, T-Tsujii requested changes

2021-03-19 10:07 UTC, T-Tsujii commented on spec/models/movie_spec.rb
> +  describe "def watched_by?(user)" do
`"def watched_by?(user)"` の箇所は `.watched_by?` や `#watched_by?` と書くことが多いですね。

2021-03-19 10:07 UTC, T-Tsujii commented on spec/models/movie_spec.rb
> +        expect(watched_movie.present?).to be_truthy
肝心の `watched_by?` メソッドを使用してないのではありませんか？

2021-03-19 10:07 UTC, T-Tsujii commented on spec/models/movie_spec.rb
> +      movie = create(:movie, genre: "test")
ここは `let` でよいですね。

2021-03-19 13:56 UTC, T-Tsujii requested changes

2021-03-19 13:56 UTC, T-Tsujii commented on spec/models/movie_spec.rb
> +        expect(movie.watched_by?(user)).to be_falsey
微妙なラインですが，念のため user 以外の watched を作成しておいた方がよいでしょう。

2021-03-19 14:38 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-21 03:45 UTC, gorgonzola731 approved these changes
LGTMです！

2021-03-21 08:45 UTC, zenfumi approved these changes
LGTMです！

2021-03-24 03:22 UTC, merged