各教材ページのタイトルを genresテーブル参照に変更
yanbaru-expert/team_project_43 pull request #86
Opened 2021-03-24 04:06 UTC by ao21

## 85
close #85 

## 実装内容
- 各教材ページのタイトルを genres モデルより取得するように変更

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-03-24 05:18 UTC, T-Tsujii requested changes

2021-03-24 05:18 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +    <h1><%= text_title %></h1>
この形式にすれば `genre_title` メソッドを用意するだけでよくなりますよ。

```suggestion
    <h1><%= "#{genre_title} テキスト教材" %></h1>
```

2021-03-24 07:46 UTC, T-Tsujii approved these changes
LGTMです！

2021-03-25 07:51 UTC, gorgonzola731 approved these changes
LGTMです！

2021-03-26 13:54 UTC, zenfumi approved these changes
LGTMです！

2021-04-06 05:13 UTC, merged